x-meshmvc:
  #Title of your application
  site_name: MeshMVC

  #output errors and prevent redirecting and displaying an error page
  debug: true

  default_logger: logger
  logs:
    access_logs: "logs/access.log"
    error_logs: "logs/errors.log"

  #REQUIRED: directories search patterns
  seeds:
    #views search pattern
    - storage:*.*
    #views search pattern
    - view:*.php
    #views search pattern
    - template:*.*
    #controllers search pattern
    - controller:*.php
    #css auto-discovery search pattern
    - css:*.css
    #js auto-discovery search pattern
    - js:*.js
    #media files search pattern
    - media:*.*

  default_storage: fs
  storage:
    #alias
    sftp:
      #storage type
      sftp:
        HOST: access801578065.webspace-data.io
        PORT: 22
        USER: acc217532997
        PASSWORD: "!!DASADSjkasd56456"
    #alias
    curl:
      #storage type
      curl: ~
    #alias
    fs:
      #storage type
      local: ~
    #alias
    sql:
      #storage type
      mysql: &mysql
        MYSQL_DATABASE: meshmvc_db
        MYSQL_HOST: localhost
        MYSQL_USER: meshmvc
        MYSQL_PASSWORD: "changeme"
    #alias
    s3:
      #storage type
      s3: ~
    #alias
    zip:
      #storage type
      zip: ~
x-defaults:
  network: &network
    networks:
      - net
services:
  meshmvc:
    build: ./docker
    ports:
      - 80:80
    volumes:
      - ./www/:/var/www/html
      - ./:/var/www/
      - ./mysqldata:/var/lib/mysql
    extra_hosts:
      - host.docker.internal:host-gateway
    <<: *network

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      <<: *mysql
    <<: *network

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - "db"
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8888:80"
    <<: *network

networks:
  net:
